pipeline:
  name: pl_auto_pipeline_YbyNd
  identifier: pl_auto_pipeline_YbyNd
  projectIdentifier: Github_Connector_pipeline
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: A1
        identifier: A1
        description: new pipeline Gitx update
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: Q1
                  identifier: Q1
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: <+input>
                      disallowPipelineExecutor: false
                      userGroups: <+input>
                    approverInputs: []
                  when:
                    stageStatus: All
                  failureStrategies:
                    - onFailure:
                        errors:
                          - AllErrors
                        action:
                          type: MarkAsSuccess
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: MarkAsSuccess
