pipeline:
  name: pl_auto_pipeline_fvJlD
  identifier: pl_auto_pipeline_fvJlD
  projectIdentifier: ba
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: A1
        identifier: A1
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: A2
                  identifier: A2
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: echo amit
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
